# Windows rules
# windowrule = suppressevent maximize, class:.* # You'll probably like this.
windowrule = idleinhibit fullscreen, class:.* # Inhibit idle if there's a fullscreen app
# Clipse
windowrule = float,class:(clipse) # ensure you have a floating window class set if you want this behaviour
windowrule = size 622 652,class:(clipse) # set the size of the window as necessary
# Neovim
#windowrule = noborder, class:kitty, title:nvim
# Games
# windowrule = immediate, class:steam_app.*

# Workspaces rules
# workspace = 1, monitor:DP-3, default:true
# workspace = 2, monitor:DP-2, default:true
